### ISSUE TITLE
Bumps bounds of packages not getting tested

### ISSUE THREAD

**Issue by ysangkok** [nomeata/haskell-bounds-bump-action#2]
To work around the limitation in #1, I inlined the action, and changed the default working directory to just cover the `core` directory. But now I have another, distinct, issue: servant doesn't work with aeson-2.2. I don't wanna attempt compiling servant with aeson-2.2 in the CI suite for servant-swagger-ui (which is in a different repo). But looking at [the logs](https://github.com/haskell-servant/servant-swagger-ui/actions/runs/5521728322/jobs/10070265484), it looks like this is what the bump-action is attempting.

I suppose that it could make sense to update bounds of leaf packages even though the bounds of parent packages haven't been bumped yet. So it might make sense to override bounds of parent packages. But if it fails compiling the parent package, I don't think it should cause the leaf test suite to fail.

I see the item called "Why bump all dependencies together?" in the README, and I wonder whether it might make sense to also make this option configurable. If the option is set to "allow-newer only on leaf package", and it fails to find a build plan, the test suite would succeed. This would allow for less noise for the "non-happy" path. I am not sure it is best to optimize for the happy path since many packages depend on packages that depend on popular packages like bytestring and aeson. This means that for most leaves, if a bound is set for aeson, it might very well be a bound that can't just be ignored. I'd consider it more conservative to bump only for leaves.

**Comment by nomeata** [comment]
Hi, and good to have these discussions!

I see good arguments for both variants.

If you have a dependency (here servant) that doesn't support the version of the dependency you want to upgrade (here aeson), then without `--allow-newer`, the build will just fail earlier (no build plan), but it will fail in either case, won't it?

My hope using `--allow-newer` is that in cases where `servant` happens to be compatible, we can bump our dependency even before that package sees a new release, and break the sequentiality that slows down how fast support for new packages trickle through the ecosystem.

Ah, but you say “it fails to find a build plan, the test suite would succeed”. With test suite, do you mean the bump action?

Yes, I can see an argument that it should fail more quietly in that case. Good point! 

Would you still expect it to fail loudly if it can find a build plan but the build fails?

Or maybe I should use `--dependencies-only`; failure there means stay quiet, failure with `cabal build` afterwards are worth notifying about. How does that sound?

**Comment by ysangkok** [comment]
> but it will fail in either case, won't it?

Yes, but as you observed, the failures for failing build plans are more difficult to resolve, so it makes sense to be able to distinguish them.

> you say “it fails to find a build plan, the test suite would succeed”. With test suite, do you mean the bump action?

Yes, I mean the bump action. Because I'd like the bump action to never fail, but simply sometimes make a PR, and sometimes do nothing. If it sometimes fails because of some upstream issue that I might not be able to do anything about, I am bothered for no reason. And if that upstream dependency adds compatibility, and everything goes well, the bump action might later be able to make a working PR. In the case of servant-swagger-ui-core, it would fail to build deps (e.g. `servant`) if it chose to bump `aeson`, but the day that servant updates, it would succeed here and might be able to make that PR then. And the user was never notified of any issues.

> Would you still expect it to fail loudly if it can find a build plan but the build fails?

Not sure! I could see arguments for both. If it doesn't fail loudly when a bump fails, I know that the bound is correct. (this reminds me of the recent discussion on Discourse on `<?` vs `^>=`, so there might even be a PR for the bump action to make in the future when that operator is added!). But if it does fail loudly, you'd know that it is just your library that is incompatible, which is something that should probably be handled.

Regarding whether to use `--dependencies-only`, I suppose it would be easier to use that instead of trying to find out if a build plan exists.

Here are some configuration option ideas that would handle partially handle the case of `servant-swagger-ui-core`, I believe.

* `allow-newer-for: target-only | dependencies-and-target`. If set to `target-only`, it would only generate `--allow-newer=servant-swagger-ui-core:aeson`. If set to `dependencies-and-target` (current behaviour), it would generate `--allow-newer=*:aeson`. The amount of `allow-newer`s could vary depending on the option I propose below.
* `when-dependencies-build-fails: abort-and-fail-action | abort-and-succeed-action`. When set to `abort-and-succeed-action`, it would succeed the action when the build with `--dependencies-only` fails. The  `--dependencies-only` build would always be done. When the option is `abort-and-fail-action`, it would just fail the action as it currently does.

But to make progress on `bytestring` when `aeson` is stuck, there is the combinatorial explosion to worry about. What if we just sampled at random? Given that the bump action runs repeatedly, it could still make progress eventually, if there is progress to make:

* `pick-max-X-deps-to-bump: always-pick-all | <number>`. Used to still allow for progress on other dependencies when a particular dependency gets stuck for a long time upstream. This option could have the default `always-pick-all` (current behaviour). But when set to a `<number>`, the bump action would sample at most the configured number of dependencies from the total list of outdated deps.  If set to `1`, for example, and there are two dependencies to bump (`aeson` and `bytestring`), it would pick one of these two at random. For the `servant-swagger-ui-core` case, the bump action would be able to, with 50% likelihood, of making a PR for bytestring even though `aeson` is stuck because of `servant`. So after a few weeks have passed, it is overwhelmingly likely to have made a PR with the `bytestring` bump.

Not sure whether random sampling is going to be confusing? I suppose the library could also just sort the deps to bump, and then pick the top three deps to bump.  Then it could exhaustively check those, since there are only 2*2*2=8 combinations to test. But that would require looping or repetition, and I am not sure that is comfortable to do with Actions?

> failure with cabal build afterwards are worth notifying about. How does that sound?

Given that there are users out there that simply oppose a new design and want to stick with e.g. an older `random` release, one could argue that even the failure of the build of the leaf/target package with the bump could be something the user might want to ignore. But I think this is a real edge case, and I personally don't have any `outdated` entries that aren't issues.

Another common case would be when a new `base` is released, but the compiler is still buggy and you don't wanna work on bumping your libraries yet. Users might have added the bump action because it sounded like free work, and they might just remove it if they get too many notifications for failed workflows. "I thought it would just make PRs, I didn't know it would complain too". There is something to be said for software that never fails, but occasionally sends a PR that it actually tested.

Personally, having it ignore failed builds would make it more of a no-brainer to send PRs to add the bump action to repos, because who doesn't want free work done for them? If it starts bugging them every few thursdays, they might just silence it and we lose the free work it could have done for the other deps that *could* have been updated with no build failures. Given that `<?` might be on the horizon, maybe it is better to annoy people as little as possible. In the future we will have better data, and we can tell people, "the bump action wouldn't have bothered you if you had used this operator on your upper bound instead".

However, I also think it would be fine if the bump action didn't provide a configuration option for ignoring failures with `allow-newer` for the leaf/target package, and that it just kept failing loudly. But that might just because I am too obsessed with staying current.

**Comment by nomeata** [comment]
All very good points.

I am hesitant to just throw options at the problem, and rather spend more time thinking of a mode that works well enough for almost everyone.

As for failing or succeeding the workflow, I’m leaning towards succeeding if just the dependencies cannot be built (as not necessarily actionable), but failing if your package cannot be built (usually actionable). I’m worried that we’ll see cases where the action simply doesn't work for some reason, but it won’t be noticed this way. But probably better than being annoying.

I fear that testing random subsets of packages will lead to very unpredictable behavior. Leaning towards always aiming for the latest. And I think I’ll simply not include “users out there that simply oppose a new design” in the target audience (or rather, include them in the target audience that is invited to just copy the workflow and adjust to their needs). Same with people who don't want to upgrade to a new GHC release yet.

I wonder if there is a way to prevent an email notification, but still list it as “something not great” in the list of actions.

**Comment by nomeata** [comment]
I’m anyway doubtful if this approach (cronjob tests bump, then creates PR) is the right approach, and if the better approach is not

 * create bumping PRs untested (possibly even separate ones for each dependency)
 * ensure that CI test upper bounds reliably

I have prototyped the latter with this tool: https://github.com/nomeata/cabal-force-upper-bound

Then open PRs are a reminder of bumps that need to happen eventually, and their status accurately tells you if they can be bumped already.

**Comment by nomeata** [comment]
I’m experimenting with some improvements against your repo at <https://github.com/haskell-servant/servant-swagger-ui/compare/bumper...nomeata:servant-swagger-ui:bumper>. It may make sense to come up with a decent setup that works for you, and then see what of if we want to generalize to the default action.

**Comment by nomeata** [comment]
seems to be working. Feel free to pull from that branch before Thursday :-)

**Comment by nomeata** [comment]
I think the actionable parts were in #3, so closing this. Feel free to reopen if this was premature.
