### ISSUE TITLE
Build dependencies separately

### ISSUE THREAD

**Issue by nomeata** [nomeata/haskell-bounds-bump-action#3]
https://github.com/nomeata/haskell-bounds-bump-action/issues/2 has good discussion, so let’s break actionable items into separate issues.

Sometimes a bump doesn't work because a dependency can’t be built with it yet (using `--allow-newer`). To make the action less noisy, it should

 * first build with `--dependencies-only`.
 * if that fails, abort the workflow with status “success”.
 
This possibly needs to be configurable, but maybe not initially.

Prototyping this at https://github.com/haskell-servant/servant-swagger-ui/compare/bumper...nomeata:servant-swagger-ui:bumper

**Comment by ysangkok** [comment]
I've merged your branch and it seems to work fine so far!

**Comment by nomeata** [comment]
Sounds good!
