### ISSUE TITLE
Extend upper bound range rather then using or and carrot

### ISSUE THREAD

**Issue by jappeace** [nomeata/haskell-bounds-bump-action#5]
In this [PR](https://github.com/snoyberg/keter/pull/279) the build failed because the lts hadn't included the patches yet
```
        In the dependencies for keter-2.1.1:
           transformers-0.6.1.0 from Stack configuration does not match
                                >=0.5.6 && <0.6 || ^>=0.6.1.1 (latest matching version is 0.6.1.1)
           unix-2.8.1.0 from Stack configuration does not match >=2.7.2 && <2.8 || ^>=2.8.1.1
                        (latest matching version is 2.8.1.1)
       needed since keter is a build target.
       
```

I solved it [manually](https://github.com/snoyberg/keter/pull/279/commits/291f7aa3e8058db7bbc8b052822ce17c358fc9b3) by using ranges instead, so instead of:
```
transformers >=0.5.6 && <0.6 || ^>=0.6.1.1,
```
where `|| ^>=0.6.1.1` was added by the action,
I changed it to:
```
transformers >=0.5.6 && <0.7,
```

Would it be possible to do this automatically? So I only have to check CI and the respective change logs?

**Comment by nomeata** [comment]
I think the problem is rather something else:  This action assumes you are building with cabal against hackage, and tries to bump to the latest version from Hackage.

But it seems you want to build against the latest lts. So the dependency bump shouldn’t even look what’s on hackage, but merely what’s in the latest lts, and only bump to that.

Does that make sense?

**Comment by jappeace** [comment]
I see,
then my quesstion is "how can we make it work with stack?" :sweat_smile: 

I didn't even realize it was building with stack. Makes sense since it's originally a snoyberg project.

**Comment by nomeata** [comment]
So, in this particular case one could argue that my tool should say
```
transformers >=0.5.6 && <0.6 || ^>=0.6.1,
```
i.e. don’t include the patch level in the version. This would have helped here (but not in general if stack is behind by a minor version).

Another response could be that in such a case, one could simply wait for stack to include the new version?

**Comment by nomeata** [comment]
I’ve done the former, so that at least patch-level differences don’t matter.

**Comment by jappeace** [comment]
this is solved then, thank you!
