### ISSUE TITLE
Why is it not bumping opt-parse applicative?

### ISSUE THREAD

**Issue by jappeace** [nomeata/haskell-bounds-bump-action#6]
It correctly found both [aeson and hedgehog](https://github.com/sthenauth/zxcvbn-hs/pull/17)

However [stackage says](https://github.com/commercialhaskell/stackage/pull/7019) I also need to bump opt-parse applicative:
```
optparse-applicative-0.18.1.0 ([changelog](http://hackage.haskell.org/package/optparse-applicative-0.18.1.0/changelog)) (Grandfathered dependencies) is out of bounds for:
- [ ] zxcvbn-hs-0.3.3 (>=0.14 && < 0.18). Jappie Klooster <hi@jappie.me> @jappeace. Used by: executable

```
 which has released [0.18.1.0](https://hackage.haskell.org/package/optparse-applicative-0.18.1.0).
 Why is this missed?
 
 (sorry for all the issues btw, I'm just running into things while using it)

**Comment by nomeata** [comment]
Thanks for testing this (rather new) tool.

It gets the list of outdated dependencies from `cabal outdated`. If you run this locally, will it complain about `optparse-applicative`? It might be because it's a dependency of your binaries only, and they are only built if the `tools` flag is on, and it's off by default.

**Comment by jappeace** [comment]
can I set a flag?

**Comment by nomeata** [comment]
It seems that `cabal outdated` doesn’t support flags, maybe report this as a bug against cabal? You could also try setting it in a `cabal.project` and see if that helps.

Or alternatively build the tools by default, or put them in a separate project.

**Comment by jappeace** [comment]
I removed upper bounds from tools.
I don't think it's a major concern
